Ecomproject/Ecomapp/urls.py
from django.urls import path,include

from Ecomapp import views
app_name='Ecomapp'
urlpatterns = [

    path('',views.AllProdCat,name='AllProdCat'),
    path('<slug:c_slug>/',views.AllProdCat,name='products_by_cat'),
    path('<slug:c_slug>/<slug:product_slug>/',views.ProdDetail,name='ProdDetails'),
]

Ecomproject/Ecomproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include


from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include('Ecomapp.urls')),
    path('search/',include('searchapp.urls')),
    path('cart/',include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Ecomproject/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [

    path('add/<int:product_id>/', views.add_cart, name="add_cart"),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name="cart_remove"),
    path('full_remove/<int:product_id>/',views.full_remove,name="full_remove")
]

Ecomproject/searchapp/urls.py
from django.urls import path

from . import views
app_name = 'searchapp'

urlpatterns = [

    path('',views.Searches,name='searchresult'),

]

Ecomproject/Ecomapp/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250,unique=True)
    desc = models.TextField()
    image = models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('Ecomapp:products_by_cat',args=[self.slug])

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250,unique=True)
    desc = models.TextField()
    image = models.ImageField(upload_to='product',blank=True)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_url(self):
        return reverse('Ecomapp:ProdDetails',args=[self.category.slug,self.slug])

    def __str__(self):
        return self.name

Ecomproject/cart/models.py
from django.db import models
from Ecomapp.models import Product
# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now=True)

    class Meta:
        db_table='Cart'
        ordering=['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)

class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)
    class Meta:
        db_table='CartItem'
    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

Ecomproject/searchapp/models.py
from django.db import models

# Create your models here.

Ecomproject/Ecomapp/views.py
from django.shortcuts import render, get_object_or_404
from . models import Category,Product

# Create your views here.
def demo(request):
    return render(request,'hello.html')

def AllProdCat(request,c_slug=None):
    products = None
    c_page = None
    if c_slug != None:
        c_page = get_object_or_404(Category,slug=c_slug)
        products = Product.objects.all().filter(category=c_page,available=True)
    else:
        products = Product.objects.all().filter(available=True)
    return render(request,'category.html',{'category':c_page,'products':products})

def ProdDetail(request,c_slug,product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

Ecomproject/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from Ecomapp.models import Product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.
def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request,product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save(),
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')

def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))

def cart_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product,id=product_id)
    cart_item = CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def full_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product,id=product_id)
    cart_item = CartItem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

Ecomproject/searchapp/views.py
from django.db.models import Q
from django.shortcuts import render
from Ecomapp.models import Product

# Create your views here.
def Searches(request):
    query = None
    products = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__icontains=query) | Q(desc__icontains=query))
    return render(request, 'search.html', {'query': query, 'products': products})

Ecomproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
{% include 'header.html' %}
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
<!--{% include 'footer.html' %}-->
</body>
</html>

Ecomproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

                 This is the Cart page. Proceed to review your items.

{% endblock %}
{% block title %}
    Cart-Green shop
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Your shopping Cart is Empty</h1>
        <br>
        <p class="text-center">
            Please Click <a href="{% url 'Ecomapp:AllProdCat' %}">Here</a>to continue your shopping.
        </p>

    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center ">
            Your shopping Cart
        </h1>
        <br>
    </div>
</div>
<div class="row mx_auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table ">
        <thead class="my_custom_thead">
        <tr>
         <th colspan="5">
             Your items
         </th>
        </tr>
        </thead>
           <tbody>
           {% for cart_item in cart_items %}
           <tr>
<!--               <td>-->
<!--                   <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}" alt="" style="width:100px;height:100px;" class="float-left rounded custom_image"></a>-->

<!--               </td>-->
               <td class="text-lef">
                   {{cart_item.product.name}}
                   <br>
                   SKU: {{cart_item.product.id}}
                   <br>
                   Price: $ {{cart_item.product.price}}
                   <br>
                   Qty: {{cart_item.quantity}} x $ {{cart_item}}

               </td>
               <td>
                   $ {{cart_item.sub_total}}
               </td>
               {% if cart_item.quantity < cart_item.product.stock %}
               <td>
                   <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"> <i class="fas fa-plus custom_icon"></i></a>
                   &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fas fa-minus custom_icon"></i></a>
                   &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa-trash custom_icon"></i></a>
               </td>
               {% else %}
               <td>

                   &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fas fa-minus custom_icon"></i></a>
                   &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa-trash custom_icon"></i></a>
               </td>
               {% endif %}
           </tr>
           {% endfor %}
           </tbody>
        </table>

    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th>
                    Checkout
                </th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    Please review your shopping cart items before proceeding with the order payment.
                </td>
            </tr>
            <tr>
                <td class="text-left">
                    Your Total is : <strong>{{ total }}</strong>
                </td>
            </tr>
            </tbody>
        </table>
        <div class="mx_auto">
            <a href="{% url 'Ecomapp:AllProdCat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
        </div>
        {% endif %}
     </div>
    </div>



{% endblock %}

Ecomproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
{% if category %}
    {{category.description}}
{% else %}
    Welcome to Ecommerce App
{% endif %}

{% endblock %}

{% block title %}
{% if category %}
    {{category.name}}
{% else %}
    Our Category
{% endif %}
{% endblock %}

{% block content %}
{% if category %}
    <div>
        <div>
<!--            <p><a href="{% url 'Ecomapp:AllProdCat' %}">our products11 </a>"</p>-->
        </div>
    </div>
{% endif %}

<div>
    {% if category %}
        <img src="{{category.image.url}}" alt="{{category.name}}" style="width:100%;height:370px;">
</div>

<br>

<div>
    <h2>{{category.name}}</h2><br>
    <p>{{category.desc}}</p>

</div>
    {% else %}
<div>
    <img src="{% static 'img/banner.jpg'  %}" alt="our products" style="width:100%;height:350px;">
</div><br>
<div>
    <h2 style="text-align:center;">our products</h2>
    <p>E-commerce, or electronic commerce, refers to the buying and selling of
        goods and services over the internet. It encompasses a wide range of online
        business activities, from retail shopping to auctioning and payment services.
        Here's a detailed overview </p>

</div>
{% endif %}
<div>
    <div class="container">
        <div class="row">
            {% for product in products %}
            <div class="col-md-4">

                <div>
                    <div>
                        <a href="{{product.get_url}}"><img src="{{product.image.url}}" alt="{{product.name}}"></a>
                        <div>
                            <h2>{{product.name }}</h2>
                            <p>{{product.price}}</p>
                            <p>{{product.desc}}</p>
                        </div>
                    </div>
                </div>

            </div>
            {% endfor %}
            </div>
        </div>

</div>
{% endblock %}

Ecomproject/templates/footer.html
<div class="footer navbar-fixed-bottom">

    <p style="text-align:center; padding-top:20px;"> &copy; right reserved</p>

</div>

Ecomproject/templates/header.html
{% load static %}

<header>
  <center>
    <a href="{% url 'Ecomapp:AllProdCat' %}"><img src="{% static 'img/logo.png' %}" alt="logimage" style="width:150px;"></a>
  </center>
</header>

Ecomproject/templates/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>hello</h1>
</body>
</html>

Ecomproject/templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</head>



<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'Ecomapp:AllProdCat' %}">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">


        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'Ecomapp:AllProdCat' %}">All Products</a></li>
            {% for cat in links %}

            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>

            {% endfor %}

          </ul>
        </li>
        <li class="nav-item">
<!--          <a class="nav-link disabled" aria-disabled="true">Disabled</a>-->
          <a class="navbar-brand btn btn-danger" href="{% url 'cart:cart_detail' %}">Cart</a>
        </li>
      </ul>
      <form class="d-flex" role="search" action="{% url 'searchapp:searchresult' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>



<!--<nav>-->
<!--  <ul>-->
<!--    <li><a href="{% url 'Ecomapp:AllProdCat' %}">All Products1</a> </li>-->
<!--    {% for cat in links %}-->
<!--    <li><a href="{{cat.get_url}}">{{cat.name}}</a></li>-->
<!--    {% endfor %}-->
<!--  </ul>-->
<!--</nav>-->

Ecomproject/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!--<div>-->
<!--    <a href="{% url 'Ecomapp:AllProdCat' %}">All Products</a> <br>-->
<!--    <a href="{{ product.category.get_url}}">{{product.category}}</a>-->
<!--</div>-->
<div class="container">
    <div class="card">
        <div class="card-body">

                    <div style="text-align:center;">
                        <img  src="{{product.image.url}}" alt="{{product.name}}">
                    </div>

                <div>
                    <h2 style="text-align:center;">{{product.name}}</h2>
                    <p style="text-align:center;">${{product.price}}</p>
                    <p>{{product.desc}}</p>
                    {% if product.stock <= 0 %}
                    <p><b>Out of Stock</b></p>
                    {% else %}
                    <a class="btn btn-success" href="{% url 'cart:add_cart' product.id %}">Add to Cart</a>
                    {% endif %}
                </div>
        </div>
    </div>
</div>
{% endblock %}

Ecomproject/templates/search.html
{% extends 'base.html' %}

{% block content %}

{% if query %}
        <div class="container">
            <div class="card">
                <div class="card-body">
                    <p style="text-align:center;"><b>You Searched for {{query}}</b></p>
                    {% if products %}
                        {% for product in products %}
                            <div>
                                <div style="text-align:center;">
                                    <a href="{{product.get_url}}"><img  src="{{product.image.url}}" alt="{{product.name}}"></a>
                                    <div>
                                        <h2 style="text-align:center;">{{product.name }}</h2>
                                        <p style="text-align:center;">{{product.price}}</p>
                                        <p>{{product.desc}}</p>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                        <P style="text-align:center;"><b>{{query}}: No results</b></P>
                    {% endif %}
                </div>
            </div>
        </div>

{% else %}
    <div class="container">
      <P><b>{{query}}: No results</b></P>
    </div>




{% endif %}



{% endblock %}